name: Bump Version
on:
  push:
    branches:    
      - master         # Push events on master branch
jobs:
  Ubuntu:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: no tag
      uses: nuxt/actions-yarn@node-10
      with:
        args: "config set version-commit-hooks false"
       
    - name: no tag
      uses: nuxt/actions-yarn@node-10
      with:
        args: "version --patch"
      
    - uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        commit_author_email: github@action.com
        commit_author_name: Github Action
        commit_message: Bump patch version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
